create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  phone text,
  status text not null default 'disconnected' check (status in ('disconnected','qr','connecting','connected')),
  qr_string text,
  ai_enabled boolean not null default true,
  ai_status text not null default 'active' check (ai_status in ('active','paused')),
  ai_error text,
  system_prompt text not null,
  created_at bigint not null default extract(epoch from now())::bigint,
  updated_at bigint not null default extract(epoch from now())::bigint
);

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  phone text not null,
  name text,
  mode text not null default 'AI' check (mode in ('AI','HUMAN')),
  label text,
  pipeline_stage text not null default 'Nuevo cliente',
  last_message_at bigint,
  created_at bigint not null default extract(epoch from now())::bigint,
  unique(account_id, phone)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  role text not null check (role in ('user','assistant','human')),
  content text not null,
  media_url text,
  media_type text,
  created_at bigint not null default extract(epoch from now())::bigint
);

create table if not exists public.outbox (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  phone text not null,
  content text not null,
  media_url text,
  media_type text,
  sent boolean not null default false,
  created_at bigint not null default extract(epoch from now())::bigint
);

create table if not exists public.account_restart (
  account_id bigint primary key references public.accounts(id) on delete cascade,
  requested_at bigint not null default extract(epoch from now())::bigint
);

create table if not exists public.quick_replies (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  title text not null,
  text text not null,
  sort_order integer not null default 0,
  created_at bigint not null default extract(epoch from now())::bigint,
  updated_at bigint not null default extract(epoch from now())::bigint
);

create table if not exists public.customer_profiles (
  conversation_id bigint primary key references public.conversations(id) on delete cascade,
  customer_name text,
  project_type text,
  city text,
  budget text,
  measurements text,
  visit_date text,
  notes text,
  updated_at bigint not null default extract(epoch from now())::bigint
);

create table if not exists public.payment_links (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  preference_id text not null unique,
  title text not null,
  amount numeric not null,
  currency text not null default 'MXN',
  status text not null default 'pending',
  init_point text not null,
  created_at bigint not null default extract(epoch from now())::bigint,
  updated_at bigint not null default extract(epoch from now())::bigint
);

create index if not exists idx_conversations_account on public.conversations(account_id);
create index if not exists idx_messages_conv on public.messages(conversation_id, created_at);
create index if not exists idx_messages_conversation_id on public.messages(conversation_id);
create index if not exists idx_outbox_pending on public.outbox(sent, created_at);
create index if not exists idx_outbox_account on public.outbox(account_id);
create index if not exists idx_outbox_conversation on public.outbox(conversation_id);
create index if not exists idx_quick_replies_account on public.quick_replies(account_id, sort_order, id);
create index if not exists idx_customer_profiles_conversation on public.customer_profiles(conversation_id);
create index if not exists idx_payment_links_conversation on public.payment_links(conversation_id, created_at);

alter table public.accounts enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.outbox enable row level security;
alter table public.account_restart enable row level security;
alter table public.quick_replies enable row level security;
alter table public.customer_profiles enable row level security;
alter table public.payment_links enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'whatsapp-media',
  'whatsapp-media',
  false,
  33554432,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'text/csv',
    'text/plain',
    'application/zip',
    'video/mp4',
    'audio/ogg',
    'audio/mpeg',
    'audio/mp4',
    'audio/aac',
    'audio/webm',
    'audio/wav',
    'audio/x-wav'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
