create table if not exists public.payment_links (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  preference_id text not null unique,
  title text not null,
  amount numeric not null,
  currency text not null default 'MXN',
  status text not null default 'pending',
  init_point text not null,
  created_at bigint not null default extract(epoch from now())::bigint,
  updated_at bigint not null default extract(epoch from now())::bigint
);

create index if not exists idx_payment_links_conversation
  on public.payment_links(conversation_id, created_at);

alter table public.payment_links enable row level security;
