create table if not exists public.reminders (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  message text not null,
  due_at bigint not null,
  status text not null default 'pending' check (status in ('pending','sent','cancelled')),
  created_at bigint not null default extract(epoch from now())::bigint,
  sent_at bigint
);

create index if not exists idx_reminders_due
  on public.reminders(account_id, status, due_at);

alter table public.reminders enable row level security;

drop policy if exists "Service role can manage reminders" on public.reminders;
create policy "Service role can manage reminders"
  on public.reminders
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
