create table if not exists public.conversation_aliases (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  alias text not null,
  created_at bigint not null default extract(epoch from now())::bigint,
  unique(account_id, alias)
);

create index if not exists idx_conversation_aliases_account_alias
  on public.conversation_aliases(account_id, alias);

create index if not exists idx_conversation_aliases_conversation
  on public.conversation_aliases(conversation_id);

insert into public.conversation_aliases (account_id, conversation_id, alias)
select account_id, id, phone
from public.conversations
on conflict (account_id, alias) do nothing;

alter table public.conversation_aliases enable row level security;

drop policy if exists "Service role can manage conversation aliases" on public.conversation_aliases;

create policy "Service role can manage conversation aliases"
  on public.conversation_aliases
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
